# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ef6ca454cf6a38d903004832f559d93c22a91588501c59ec50b3e5c266d320ffed73cdf0731e5fa86cd1b1cb9addbdd05727146112e069ed5cb3f8ff0c36351

test:
  secret_key_base: 0a6f68af0296627d9a707c9c70e91e75e19b1f9edb30d6e68190e54b810ee5798d1ef507e7a256112791e8f3c4d06a501b2ff9c3da639099005ded22fab341ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
